# Generated by Django 4.2.4 on 2023-09-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_rename_image_product_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=900)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Keyword',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='SubCategory',
            field=models.ManyToManyField(blank=True, to='Ecommerce.productsubcategory'),
        ),
    ]
