# Generated by Django 4.2.4 on 2023-09-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_product_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=2000)),
                ('Text', models.TextField(max_length=10000)),
            ],
        ),
    ]
