# Generated by Django 4.0.10 on 2024-03-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Sizes',
            new_name='Available',
        ),
    ]
